### ISSUE TITLE
MikTeX vs. TeXLive

### ISSUE THREAD

**Issue by Pegasus01123** [UweZiegenhagen/FUH-LaTeX-2020#1]
Hallo, ich hatte auf meinem Computer ja das Problem, das mir MikTeX das TeXLive überschrieben hat. Auf dem Laptop habe ich das gleiche Problem und kann mich nicht mehr daran erinnern, wie wir das gelöst haben. Können sie mir noch mal eine Anleitung schicken? 
Ann-Christin Falkenreck

**Comment by UweZiegenhagen** [comment]
Hi Ann-Christin, der Pfad zu TeXLive (vermutlich C:\texlive\2020\bin\win32) muss vor MikTeX in der Umgebungsvariablen PATH stehen. Mehr dazu z.B. unter https://www.java.com/de/download/help/path.html

**Comment by Pegasus01123** [comment]
Danke, mit der Hilfe sollte es funktionieren


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Uwe Ziegenhagen<mailto:notifications@github.com>
Gesendet: Freitag, 8. Jänner 2021 21:54
An: UweZiegenhagen/FUH-LaTeX-2020<mailto:FUH-LaTeX-2020@noreply.github.com>
Cc: Pegasus01123<mailto:pegasus_1685@hotmail.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [UweZiegenhagen/FUH-LaTeX-2020] MikTeX vs. TeXLive (#1)


Hi Ann-Christin, der Pfad zu TeXLive (vermutlich C:\texlive\2020\bin\win32) muss vor MikTeX in der Umgebungsvariablen PATH stehen. Mehr dazu z.B. unter https://www.java.com/de/download/help/path.html
